CREATE TABLE [MsStaff] (
	StaffID CHAR(5) PRIMARY KEY CHECK (StaffID LIKE 'ST[0-9][0-9][0-9]'),
	StaffName VARCHAR(50) NOT NULL,
	StaffGender VARCHAR(10) NOT NULL,
	StaffAddress VARCHAR(50)NOT NULL,
	StaffDOB DATE NOT NULL,
	StaffSalary FLOAT (50)NOT NULL,
	StaffPhoneNumber VARCHAR(13)NOT NULL
)
CREATE TABLE[MsGameType](
GameTypeID CHAR(5) PRIMARY KEY CHECK (GameTypeID LIKE 'GT[0-9][0-9][0-9]'),
GameTypeName VARCHAR(50)NOT NULL

)
CREATE TABLE [MsGame](
GameID CHAR(5) PRIMARY KEY CHECK (GameID LIKE 'GA[0-9][0-9][0-9]'),
GameTypeID CHAR(5) FOREIGN KEY REFERENCES MsGameType(GameTypeID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
GameName VARCHAR(50) NOT NULL,
GamePrice FLOAT(50) NOT NULL,
ReleaseDate DATE NOT NULL
)
CREATE TABLE [MsCustomer] (
	CustomerID CHAR(5) PRIMARY KEY CHECK (CustomerID LIKE 'CU[0-9][0-9][0-9]'),
	CustomerName VARCHAR(50) NOT NULL,
	CustomerGender VARCHAR(10) NOT NULL,
	CustomerDOB DATE NOT NULL,
	CustomerPhoneNumber VARCHAR(13)NOT NULL
)

CREATE TABLE[MsSupplier] (
	SupplierID CHAR(5) PRIMARY KEY CHECK (SupplierID LIKE 'SU[0-9][0-9][0-9]'),
	SupplierName VARCHAR(50)NOT NULL,
	SupplierAddress VARCHAR(50)NOT NULL,
	SupplierPhoneNumber VARCHAR(13)NOT NULL

)

CREATE TABLE [PurchaseHeader] (
	PurchaseID CHAR(5) PRIMARY KEY CHECK (PurchaseID LIKE 'PU[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	SupplierID CHAR(5) FOREIGN KEY REFERENCES MsSupplier(SupplierID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PurchaseDate DATE NOT NULL
	
)

CREATE TABLE [PurchaseDetail] (
	PurchaseID CHAR(5) FOREIGN KEY REFERENCES PurchaseHeader(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	GameID CHAR(5) FOREIGN KEY REFERENCES MsGame(GameID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	Quantity INT NOT NULL CHECK (Quantity > 0)
)

CREATE TABLE [SalesHeader](
SalesID CHAR(5) PRIMARY KEY CHECK (SalesID LIKE 'SA[0-9][0-9][0-9]'),
StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
CustomerID CHAR(5) FOREIGN KEY REFERENCES MsCustomer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
SalesDate DATE NOT NULL

)

CREATE TABLE[SalesDetail](
SalesID CHAR(5) FOREIGN KEY REFERENCES SalesHeader(SalesID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
GameID CHAR(5) FOREIGN KEY REFERENCES MsGame(GameID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
Quantity INT NOT NULL CHECK (Quantity > 0)

)